Modified isStopped() check to support draining in progress requests.
xedin/disruptor_thrift_server pull request #14
Opened 2017-06-27 22:37 UTC by sotodel

Trying to solve https://issues.apache.org/jira/browse/CASSANDRA-13137.

I believe the intended behavior of stopping the `TDisruptorServer` was to drain all ongoing requests. This code should achieve that.

I've added a check within `Message` that reports the message activity state, if it is currently being processed: started reading, started writing, or being processed by a `TProcessor`. 

In the `TDisruptorServer`, we make that check once the `isStopped` flag is set to `true`. We only stop the selector loop if the server is stopped and all messages are inactive.

I could remove the preemptive `cleanupSelectionKey` calls, but we would potentially be scanning over many more elements to find one that is active.

2017-06-27 22:57 UTC, sotodel commented
An alternative is having a dedicated `select` loop in each subclass. We could do this check more efficiently under `SelectorThread` if that was the case. There would just be a bit of code duplication.

2017-07-01 06:13 UTC, xedin approved these changes
Overall LGTM, expect for the code style in `Message.java`.

2017-07-01 06:13 UTC, xedin commented on src/main/java/com/thinkaurelius/thrift/Message.java
> +    public boolean isActive(){
Could you please make it the same style as the rest of the code?

2017-07-01 06:15 UTC, xedin commented
@sotodel Thanks for the work!

2017-07-01 15:32 UTC, sotodel commented
Thanks for the review, @xedin. Resubmitted with the change, brackets and indentation of `case`?

Just checking, `cleanupSelectionKey` might be called multiple times for the same `SelectionKey`. Will that be a problem for `Message#close` and the cleanup it does?

2017-07-02 05:13 UTC, xedin commented
@sotodel This is a very good point actually (it's been a while since I last looked at this code). It looks like you'll have to do a bit more work to make this happen - add a new state to message which identifies it as closed and check for that state in `Message#close`, another way to do this might be for `cleanupSelectionKey` to reset `attachment` to `null` but it would require additional null checks in `processKey` and other methods. I'd prefer the second one but it's really up to you.

2017-07-05 18:16 UTC, sotodel commented
@xedin Right. I agree and made the second change you suggested. It's really only needed in `processKey`. It's the entry point and other methods already check for a `null` attachment. Please review.

2017-07-17 00:27 UTC, xedin requested changes

2017-07-17 00:27 UTC, xedin commented on src/main/java/com/thinkaurelius/thrift/TDisruptorServer.java
> +                key.attach(null);
This has to be performed inside of `Message#close`. But the problem here is that selector's `processKey` is going to race with `key.attach(null)`,  and selector could potentially retrieve a `Message` from `key` in the middle of buffer deallocation (if `isStopped` is polled by different thread). I think you'll need to add a final state to `Message`, set it first (because it's volatile), then do `selectionKey.attach(null)` and cleanup the buffers after that.

2017-07-17 17:50 UTC, sotodel commented on src/main/java/com/thinkaurelius/thrift/TDisruptorServer.java
> +                key.attach(null);
`isStopped` should only ever be called by the selector threads (can make it `protected` and add comment to signal that). I don't see that race. There's a one to one mapping between `SelectorThread` and `Message`. Calls to `processKey` and `isStopped` happen in the same thread, sequentially.

During reads, the selector thread is doing all the `state` transitions so it always sees a correct value and `isActive` will return `true`, ie. "don't stop yet". It'll finally transition the `Message` into the `READ_FRAME_COMPLETE` state. At that point, the `Message` is passed to another thread for processing. That `state` value is still "active" from the selector thread so we're still good. That other thread will eventually call `responseReady` which will `switchToWrite` which will modify the `state` and notify the selector thread through adding to its interest ops and calling `wakeup`. If the selector thread was running, it won't necessarily see the `state` value change until it goes back into its `select` loop (and actually synchronizes with that change). `state`, whether it has transitioned to `READY_TO_WRITE` or not doesn't matter, however, since that's considered "active" from the selector point of view. It'll loop until it's written the entire content and only then consider the message to "inactive". 

Unless I'm misunderstanding the synchronization of the `Selector`, I think we're good.

2017-07-18 01:50 UTC, xedin commented on src/main/java/com/thinkaurelius/thrift/TDisruptorServer.java
> +                key.attach(null);
If `isStopped` is only intended to be used by selector thread itself then it's okay. It's just making it public doesn't guarantee that. If you make it protected (or even private if possible) and mention supposed usage that would be perfect!

2017-07-18 02:32 UTC, sotodel commented on src/main/java/com/thinkaurelius/thrift/TDisruptorServer.java
> +            if (selector.selector.isOpen())
@xedin  Changed this not to use the `isStopped`. It should instead check that status of the selector. Since the selector threads control their selectors, `isOpen` will only be `false` once the threads end their loop.

2017-07-18 02:37 UTC, sotodel commented on src/main/java/com/thinkaurelius/thrift/TDisruptorServer.java
> +            if (selector.selector.isOpen())
Only slightly annoying thing remaining is the existence of `AbstractSelectorThread#close`. The selector thread loops use it to close their selector and that's how it should be but it's `public`. Still, it's `public` in a `protected` inner class, not much can leak from that. The current implementation uses it appropriately. No other thread tries to call that `close`.

2017-07-18 07:37 UTC, xedin approved these changes
LGTM!

2017-07-18 07:37 UTC, merged

2017-07-18 07:38 UTC, xedin commented
@sotodel Thanks for all the work, I'll try to release new version a bit later this week!

2017-07-18 16:46 UTC, sotodel commented
Thank you for review!

2017-08-15 15:43 UTC, sotodel commented
@xedin Did you get a chance to release?

2017-08-15 18:13 UTC, xedin commented
@sotodel Sorry I hadn't, but I'm going to, it slipped my mind unfortunately...

2017-08-16 05:01 UTC, xedin commented
@sotodel Version 0.3.9 has been released, sorry it took me a while, I completely forgot about it...

2017-08-16 15:06 UTC, sotodel commented
No problem, @xedin. In any case, Datastax folks haven't decided what to do. At least with the official release, I can manage my own builds more easily.

Thanks!